### ISSUE TITLE
PyTorch and CUDA Version

### ISSUE THREAD

**Issue by mesw** [YapengTian/TDAN-VSR#8]
At the moment, with dependencies PyTorch 0.3.1 and CUDA 75, this will not run in a colab notebook with any of the following instance types:

- none -> no cuda capable device 
- GPU -> needs at least CUDA 80
- TPU -> no cuda capable device

**Comment by YapengTian** [comment]
any errors? probably you need to compile the deformable convolution with bash make.sh.

**Comment by mesw** [comment]
when using torch==0.3.1
```
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'model.DSW' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py:95: UserWarning: 
    Found GPU0 Tesla T4 which requires CUDA_VERSION >= 9000 for
     optimal performance and fast startup time, but your PyTorch was compiled
     with CUDA_VERSION 8000. Please install the correct PyTorch binary
     using instructions from http://pytorch.org
    
  warnings.warn(incorrect_binary_warn % (d, name, 9000, CUDA_VERSION))
```

when using torch==1.1.0

```
Traceback (most recent call last):
  File "eval.py", line 10, in <module>
    from model import ModelFactory
  File "/content/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/model.py", line 7, in <module>
    from modules import ConvOffset2d
  File "/content/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/modules/__init__.py", line 1, in <module>
    from .deform_conv import ConvOffset2d
  File "/content/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/modules/deform_conv.py", line 7, in <module>
    from functions import conv_offset2d
  File "/content/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/functions/__init__.py", line 1, in <module>
    from .deform_conv import conv_offset2d
  File "/content/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/functions/deform_conv.py", line 5, in <module>
    from _ext import deform_conv
  File "/content/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/TDAN-VSR/_ext/deform_conv/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
```

**Comment by YapengTian** [comment]
For 0.3.1, the issue is from your hardware.
For 1.1.0, the issue is from deformable convolution. It does not support torch1.1. If you want to use torch1.1,  you might try other deformable convolution which supports higher version PyTorch, such as https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch/tree/pytorch_1.0.0.
